name: claimer (testnet)

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true
    - name: Restore dependencies
      run: dotnet restore
    - name: Run
      run: echo ${{ secrets.CONFIG_TESTNET }} | dotnet run --project claimer
      env:
        WIF: ${{ secrets.WIF }}
        RPC: ${{ secrets.RPC_TESTNET }}
        AGENT: ${{ secrets.AGENT_0 }}
